In [5]:
import pandas as pd

# Create a sample DataFrame (replace with your actual data)
data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob'],
    'Age': [25, 30, 28, 25, 32],
    'City': ['New York', 'London', 'Paris', 'New York', 'London'],
    'Date': ['2023-01-15', '2023-02-20', '2023-03-10', '2023-04-05', '2023-05-12']
})

data['Date'] = pd.to_datetime(data['Date']) # Convert 'Date' to datetime objects


# Now, let's demonstrate the functions:

# 1. Display the DataFrame
print("DataFrame:\n", data)

# 2. Read from CSV (replace with your file path)
# data = pd.read_csv("your_file_path.csv")
# Read a TSV file
data = pd.read_csv("/chipotle.tsv", sep="\t")

# 3. Describe numerical columns
print("\nDescription:\n", data.describe())

# 4. Shape (rows, columns)
print("\nShape:", data.shape)

# 5. Info (data types and non-null counts)
print("\nInfo:\n", data.info())

# 6. Data types of each column
print("\nData Types:\n", data.dtypes)

# 7. Head (first n rows)
print("\nHead:\n", data.head(2))

# 8. Tail (last n rows)
print("\nTail:\n", data.tail(2))

# 9. Mean of a column
#print("\nMean Age:", data['Age'].mean())

# 10. Max of a column
#print("\nMax Age:", data['Age'].max())

# 11. Value counts of a column
#print("\nValue Counts (City):\n", data['City'].value_counts())

# 12. Unique values in a column
#print("\nUnique Cities:", data['City'].unique())

# 13. Delete a column (inplace=True modifies the original DataFrame)
# del data['City']  # Or use data.drop() as shown below

# 14. Drop a column or row
data.drop(columns=['City'], inplace=True) # Drops the 'City' column
print("\nDataFrame after dropping 'City':\n", data)

data.drop(index=[1], inplace=True) # Drops the row with index 1
print("\nDataFrame after dropping row 1:\n", data)

# 15. Sort values
print("\nSorted by Age:\n", data.sort_values(by="Age"))

# 16. Read from Excel (replace with your file path)
# data = pd.read_excel("your_file_path.xlsx", index_col=0, parse_dates=["Date"])

# 17. Convert to datetime (already done above)
# data['Date'] = pd.to_datetime(data['Date'])

# 18. loc (access by label)
print("\nloc example (row 0, column 'Name'):", data.loc[0, 'Name'])

# 19. iloc (access by integer index)
print("\niloc example (row 0, column 0):", data.iloc[0, 0])

# 20. Datetime attributes (.hour, .dayofweek, etc.)
print("\nDate Hour:", data['Date'].dt.hour)
print("\nDate Day of Week:", data['Date'].dt.dayofweek)
print("\nDate Day Name:", data['Date'].dt.day_name())
print("\nDate Month:", data['Date'].dt.month)
print("\nDate Month Name:", data['Date'].dt.month_name())
print("\nDate is leap year:", data['Date'].dt.is_leap_year)
print("\nDate is month end:", data['Date'].dt.is_month_end)

# ... (rest of the functions from your list)

DataFrame:
       Name  Age      City       Date
0    Alice   25  New York 2023-01-15
1      Bob   30    London 2023-02-20
2  Charlie   28     Paris 2023-03-10
3    Alice   25  New York 2023-04-05
4      Bob   32    London 2023-05-12

Description:
           order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

Shape: (4622, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

Info:
 None

Data Types:
 order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

Head:
    order_id  quantity                     item_name choice_description  \
0         1         1  Chips and Fresh Tomato Salsa                NaN
1         1         1                          Izze       [Clementine]

  item_price
0     $2.39
1     $3.39

Tail:
       order_id  quantity           item_name  \
4620      1834         1  Chicken Salad Bowl
4621      1834         1  Chicken Salad Bowl

                                     choice_description item_price
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

KeyError: 'Age'

In [6]:
# 2. Read from CSV (replace with your file path)
# data = pd.read_csv("your_file_path.csv")
# Read a TSV file
data = pd.read_csv("/chipotle.tsv", sep="\t")

# 3. Describe numerical columns
print("\nDescription:\n", data.describe())

# 4. Shape (rows, columns)
print("\nShape:", data.shape)

# 5. Info (data types and non-null counts)
print("\nInfo:\n", data.info())

# 6. Data types of each column
print("\nData Types:\n", data.dtypes)

# 7. Head (first n rows)
print("\nHead:\n", data.head(2))

# 8. Tail (last n rows)
print("\nTail:\n", data.tail(2))

Description:
           order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

Shape: (4622, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

Info:
 None

Data Types:
 order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

Head:
    order_id  quantity                     item_name choice_description  \
0         1         1  Chips and Fresh Tomato Salsa                NaN
1         1         1                          Izze       [Clementine]

  item_price
0     $2.39
1     $3.39

Tail:
       order_id  quantity           item_name  \
4620      1834         1  Chicken Salad Bowl
4621      1834         1  Chicken Salad Bowl

                                     choice_description item_price
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

In [8]:
# Step 1: Install required libraries
import pandas as pd

# Step 2: Download the Chipotle dataset
data = pd.read_csv("/chipotle.tsv", sep="\t")

# Step 3: Display basic information
print("🔹 First 5 Rows of Dataset:")
display(data.head())

print("\n🔹 Dataset Summary:")
print(data.info())

print("\n🔹 Dataset Shape (Rows, Columns):", data.shape)

# Step 4: Basic Data Analysis
print("\n🔹 Summary Statistics for Numerical Columns:")
print(data.describe())

print("\n🔹 Unique Items Ordered:")
print(data["item_name"].nunique())

print("\n🔹 Most Ordered Items:")
print(data["item_name"].value_counts().head(10))

# Step 5: Convert item_price column to float for analysis
data["item_price"] = data["item_price"].str.replace("$", "").astype(float)

print("\n🔹 Average Item Price:", data["item_price"].mean())
print("\n🔹 Most Expensive Item Ordered:")
print(data.loc[data["item_price"].idxmax()])

# Step 6: Sorting and Filtering
print("\n🔹 Top 5 Most Expensive Orders:")
display(data.sort_values(by="item_price", ascending=False).head())

print("\n🔹 Orders with Quantity More Than 2:")
display(data[data["quantity"] > 2].head())

# Step 7: Dropping a Column (Example)
data_cleaned = data.drop(columns=["choice_description"])
print("\n🔹 Columns after dropping 'choice_description':", data_cleaned.columns)

# Step 8: Save the cleaned dataset (optional)
data_cleaned.to_csv("chipotle_cleaned.csv", index=False)

print("\n✅ Data Analysis Complete! You can now use 'data' for further exploration.")

🔹 First 5 Rows of Dataset:

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

🔹 Dataset Summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB
None

🔹 Dataset Shape (Rows, Columns): (4622, 5)

🔹 Summary Statistics for Numerical Columns:
          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

🔹 Unique Items Ordered:
50

🔹 Most Ordered Items:
item_name
Chicken Bowl                    726
Chicken Burrito                 553
Chips and Guacamole             479
Steak Burrito                   368
Canned Soft Drink               301
Steak Bowl                      211
Chips                           211
Bottled Water                   162
Chicken Soft Tacos              115
Chips and Fresh Tomato Salsa    110
Name: count, dtype: int64

🔹 Average Item Price: 7.464335785374297

🔹 Most Expensive Item Ordered:
order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
Name: 3598, dtype: object

🔹 Top 5 Most Expensive Orders:

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75

🔹 Orders with Quantity More Than 2:

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",22.20
689,284,3,Canned Soft Drink,[Diet Coke],3.75
818,338,3,Bottled Water,NaN,3.27
850,350,3,Canned Soft Drink,[Sprite],3.75

🔹 Columns after dropping 'choice_description': Index(['order_id', 'quantity', 'item_name', 'item_price'], dtype='object')

✅ Data Analysis Complete! You can now use 'data' for further exploration.